# Generated by Django 5.1.5 on 2025-01-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
