# Generated by Django 5.1.5 on 2025-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_customform_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='sumitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
